name: Tiago Dakuzaku | Full-Stack Developer
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
timezone: America/Sao_Paulo
encoding: utf-8

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      type: "curriculum"
    values:
      layout: "curriculum"

# gems: [jekyll-watch]
